# Generated by Django 3.2.8 on 2021-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='upload')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
